Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -66,7 +66,8 @@ jobs:
 
     - name: Run Unit Tests and Save Logs - Ubuntu
       id: ubuntu_result
-      if: always() && contains(matrix.os, 'ubuntu')
+      if: contains(matrix.os, 'ubuntu')
+      continue-on-error: true
       working-directory: HIRS_Provisioner.NET
       run: |
 
@@ -105,43 +106,45 @@ jobs:
         name: "${{matrix.os}}-unit-tests-${{steps.window_result.outputs.result}}.log"
         path: HIRS_Provisioner.NET/*.log
 
-    # - name: Results Passed
-    #   if: (steps.window_result.outputs.result == 'True' ||  steps.ubuntu_result.outputs.result == 'True') && always
-    #   run: |
-    #     echo "All Tests Passed"
-    #     exit 0
-
-    # - name: Results Failed
-    #   if: (steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False')  && always
-    #   run: |
-    #     echo "Unit Tests Failed"
-    #     exit 1
-
-  evaluator:
-    name: Evaluate Tests
-    needs: [dotnet_provisioner_unit_tests]
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        include:
-         # - os: windows-2022
-         # - os: ubuntu-20.04
-         - os: windows-2019
-         - os: ubuntu-18.04
-    continue-on-error: false
-    steps:
-    # - name: Results Passed
-    #   run: |
-    #     echo "fail on purpose"
-    #     exit 1
-    - name: Check If Passed
-      id: check_result
-      if: always()
-      uses: andstor/file-existence-action@v1
-      with:
-        files: "${{matrix.os}}-unit-tests-Pass.log"
-    - name: ${{matrix.os}} Unit Tests
-      if: steps.check_result.outputs.files_exists == 'false' && always()
+    - name: Results Passed
+      continue-on-error: false
+      if: (steps.window_result.outputs.result == 'True' ||  steps.ubuntu_result.outputs.result == 'True') && always
       run: |
-        echo "${{matrix.os}} Unit Tests Failed"
+        echo "All Tests Passed"
+        exit 0
+
+    - name: Results Failed
+      continue-on-error: false
+      if: (steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False')  && always
+      run: |
+        echo "Unit Tests Failed"
         exit 1
+
+  # evaluator:
+  #   name: Evaluate Tests
+  #   needs: [dotnet_provisioner_unit_tests]
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       include:
+  #        # - os: windows-2022
+  #        # - os: ubuntu-20.04
+  #        - os: windows-2019
+  #        - os: ubuntu-18.04
+  #   continue-on-error: false
+  #   steps:
+  #   # - name: Results Passed
+  #   #   run: |
+  #   #     echo "fail on purpose"
+  #   #     exit 1
+  #   - name: Check If Passed
+  #     id: check_result
+  #     if: always()
+  #     uses: andstor/file-existence-action@v1
+  #     with:
+  #       files: "${{matrix.os}}-unit-tests-Pass.log"
+  #   - name: ${{matrix.os}} Unit Tests
+  #     if: steps.check_result.outputs.files_exists == 'false' && always()
+  #     run: |
+  #       echo "${{matrix.os}} Unit Tests Failed"
+  #       exit 1
