Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -92,12 +92,20 @@ jobs:
 
     - name: Results Passed
       if: (steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True') && always()
-      run: |
-        echo "All Tests Passed"
-        exit 0
+      # run: |
+      #   echo "All Tests Passed"
+      #   exit 0
+      uses: dflydev/check-runs-action@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          conclusion: success  
 
     - name: Results Failed
       if: (steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False') && always()
-      run: |
-        echo "Unit Tests Failed"
-        exit 1
+      # run: |
+      #   echo "Unit Tests Failed"
+      #   exit 1
+      uses: dflydev/check-runs-action@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          conclusion: failure
