Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -4,7 +4,7 @@ env:
   DOTNET_VERSION: '3.1'
 jobs:
   dotnet_provisioner_unit_tests:
-    name: UnitTests
+    name: Restore and run unit tests
     # continue-on-error: true
     runs-on: ${{ matrix.os }}
     strategy:
@@ -92,22 +92,35 @@ jobs:
 
     - name: Results Passed
       if: (steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True') && always()
-      run: |
-        echo "All Tests Passed"
-        exit 0
-
-
+      # run: |
+      #   echo "All Tests Passed"
+      #   exit 0
+      # uses: dflydev/check-runs-action@v1
+      # with:
+      #   token: ${{ secrets.GITHUB_TOKEN }}
+      #   conclusion: success  
+      uses: LouisBrunner/checks-action@v1.1.1
+      if: always()
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        name: Success
+        conclusion: success
+        # output: |
+        #   {"summary":${{ steps.test.outputs.summary }}}
     - name: Results Failed
       if: (steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False') && always()
-      run: |
-        echo "Unit Tests Failed"
-        exit 1
-
-
-  evaluator:
-    runs-on: windows-latest
-    needs: [UnitTests windows-2022, UnitTests ubuntu-20.04, UnitTests windows-2019, UnitTests ubuntu-18.04]
-    steps:
-    - name: Set git to use LF
-      run: |
-        echo "Finished"
+      # run: |
+      #   echo "Unit Tests Failed"
+      #   exit 1
+      # uses: dflydev/check-runs-action@v1
+      # with:
+      #   token: ${{ secrets.GITHUB_TOKEN }}
+      #   conclusion: failure
+      uses: LouisBrunner/checks-action@v1.1.1
+      if: always()
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        name: Fail
+        conclusion: failure
+        # output: |
+        #   {"summary":${{ steps.test.outputs.summary }}}
