Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -58,20 +58,26 @@ jobs:
         Get-Content $logName
 
 
-    - name: Run Unit Tests and Save Logs - Ubuntu
+    - name: Run Unit Tests Ubuntu
       id: ubuntu_result
-      if: contains(matrix.os, 'ubuntu') && always()
+      if: contains(matrix.os, 'ubuntu')
       working-directory: HIRS_Provisioner.NET
       run: |
         logName="${{matrix.os}}-unit-tests.log"
         dotnet test --no-restore -v m > $logName
+
+    - name: Extract Ubuntu Unit Test Results
+      id: ubuntu_result
+      if: contains(matrix.os, 'ubuntu')
+      working-directory: HIRS_Provisioner.NET
+      run: |
         logName="${{matrix.os}}-unit-tests.log"
         if grep -Fxq "Passed!" $logName; 
         then 
           echo "Hit pass for ubuntu"
-          result="True"
+          result="Pass"
         else
-          result="False"
+          result="Fail"
         fi
         echo "::set-output name=result::$result"
         more $logName
@@ -79,7 +85,6 @@ jobs:
     - name: Upload Logs Ubuntu
       uses: actions/upload-artifact@v2
       if: contains(matrix.os, 'ubuntu')
-      continue-on-error: true
       with:
         name: "${{matrix.os}}-unit-tests-${{steps.ubuntu_result.outputs.result}}.log"
         path: HIRS_Provisioner.NET/*.log
@@ -92,46 +97,44 @@ jobs:
         path: HIRS_Provisioner.NET/*.log
 
     - name: Results Passed
-      continue-on-error: false
       if: (steps.window_result.outputs.result == 'True' ||  steps.ubuntu_result.outputs.result == 'True')
       run: |
         echo "All Tests Passed"
         exit 0
 
     - name: Results Failed
-      continue-on-error: false
       if: (steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False')
       run: |
         echo "Unit Tests Failed"
         exit 1
 
-  # evaluator:
-  #   name: Evaluate Tests
-  #   needs: [dotnet_provisioner_unit_tests]
-  #   runs-on: ${{ matrix.os }}
-  #   strategy:
-  #     matrix:
-  #       include:
-  #        # - os: windows-2022
-  #        # - os: ubuntu-20.04
-  #        - os: windows-2019
-  #        - os: ubuntu-18.04
-  #   continue-on-error: false
-  #   steps:
-  #   # - name: Results Passed
-  #   #   run: |
-  #   #     echo "fail on purpose"
-  #   #     exit 1
-  #   - name: Checkout repo
-  #     uses: actions/checkout@v2
-  #   - name: Check If Passed
-  #     id: check_result
-  #     if: always()
-  #     uses: andstor/file-existence-action@v1
-  #     with:
-  #       files: "${{matrix.os}}-unit-tests-Pass.log"
-  #   - name: ${{matrix.os}} Unit Tests
-  #     if: steps.check_result.outputs.files_exists == 'false' && always()
-  #     run: |
-  #       echo "${{matrix.os}} Unit Tests Failed"
-  #       exit 1
+  evaluator:
+    name: Evaluate Tests
+    needs: [dotnet_provisioner_unit_tests]
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        include:
+         # - os: windows-2022
+         # - os: ubuntu-20.04
+         - os: windows-2019
+         - os: ubuntu-18.04
+    continue-on-error: false
+    steps:
+    # - name: Results Passed
+    #   run: |
+    #     echo "fail on purpose"
+    #     exit 1
+    - name: Checkout repo
+      uses: actions/checkout@v2
+    - name: Check If Passed
+      id: check_result
+      if: always()
+      uses: andstor/file-existence-action@v1
+      with:
+        files: "${{matrix.os}}-unit-tests-Pass.log"
+    - name: ${{matrix.os}} Unit Tests
+      if: steps.check_result.outputs.files_exists == 'false' && always()
+      run: |
+        echo "${{matrix.os}} Unit Tests Failed"
+        exit 1
