Testing all Fail with File Artifact Evaluator

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -106,39 +106,39 @@ jobs:
         echo "Unit Tests Failed"
         exit 1
 
-  # Evaluator:
-  #   name: Evaluate Tests
-  #   needs: [dotnet_provisioner_unit_tests]
-  #   runs-on: ubuntu-latest
-  #   continue-on-error: false
-  #   steps:
+  Evaluator:
+    name: Evaluate Tests
+    needs: [dotnet_provisioner_unit_tests]
+    runs-on: ubuntu-latest
+    continue-on-error: false
+    steps:
 
-  #   - uses: actions/checkout@v2
+    - uses: actions/checkout@v2
 
-  #   - name: Make artifact directory
-  #     run: |
-  #       mkdir artifacts
+    - name: Make artifact directory
+      run: |
+        mkdir artifacts
 
-  #   - uses: actions/download-artifact@v3
-  #     with:
-  #       path: artifacts
+    - uses: actions/download-artifact@v3
+      with:
+        path: artifacts
 
-  #   - name: Determine if a test failed
-  #     working-directory: artifacts
-  #     run: |
-  #       result="Passed" 
-  #       suffix="-unit-tests-Fail.log"
-  #       msg=" OS did not pass all the unit tests."
+    - name: Determine if a test failed
+      working-directory: artifacts
+      run: |
+        result="Passed" 
+        suffix="-unit-tests-Fail.log"
+        msg=" OS did not pass all the unit tests."
         
-  #       # Generate Annotations and Console Output
-  #       for file in *"Fail"*.log; do
-  #         title=${file%"$suffix"}
-  #         echo "FAILED - " $title
-  #         echo "::error title='$title Unit Tests Failed'::'The $title $msg'"
-  #         result="Failed"
-  #       done
+        # Generate Annotations and Console Output
+        for file in *"Fail"*.log; do
+          title=${file%"$suffix"}
+          echo "FAILED - " $title
+          echo "::error title='$title Unit Tests Failed'::'The $title $msg'"
+          result="Failed"
+        done
         
-  #       if [ "$result" = "Failed" ]
-  #       then
-  #           exit 1
-  #       fi
+        if [ "$result" = "Failed" ]
+        then
+            exit 1
+        fi
