Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -90,14 +90,14 @@ jobs:
         name: "${{matrix.os}}-unit-tests.log"
         path: HIRS_Provisioner.NET/*.log
 
-    # - name: Results Passed
-    #   if: steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True'
-    #   run: |
-    #     echo "All Tests Passed"
-    #     exit 0
+    - name: Results Passed
+      if: steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True'
+      run: |
+        echo "All Tests Passed"
+        exit 0
 
-    # - name: Results Failed
-    #   if: steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False'
-    #   run: |
-    #     echo "Unit Tests Failed"
-    #     exit 1
+    - name: Results Failed
+      if: steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False'
+      run: |
+        echo "Unit Tests Failed"
+        exit 1
