Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -19,8 +19,9 @@ jobs:
       run: |
         git config --global core.autocrlf false
         git config --global core.eol lf
-
-    - uses: actions/checkout@v2
+    - name: Checkout repo
+      if: always()
+      uses: actions/checkout@v2
     
     - name: Restore Project
       working-directory: HIRS_Provisioner.NET
@@ -89,14 +90,14 @@ jobs:
         name: "${{matrix.os}}-unit-tests.log"
         path: HIRS_Provisioner.NET/*.log
 
-    - name: Results Passed
-      if: steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True'
-      run: |
-        echo "All Tests Passed"
-        exit 0
+    # - name: Results Passed
+    #   if: steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True'
+    #   run: |
+    #     echo "All Tests Passed"
+    #     exit 0
 
-    - name: Results Failed
-      if: steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False'
-      run: |
-        echo "Unit Tests Failed"
-        exit 1
+    # - name: Results Failed
+    #   if: steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False'
+    #   run: |
+    #     echo "Unit Tests Failed"
+    #     exit 1
