Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -102,10 +102,28 @@ jobs:
   evaluator:
     name: Evaluate Tests
     needs: [dotnet_provisioner_unit_tests]
-    runs-on: windows-latest
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        include:
+         # - os: windows-2022
+         # - os: ubuntu-20.04
+         - os: windows-2019
+         - os: ubuntu-18.04
     continue-on-error: false
     steps:
-    - name: Results Passed
+    # - name: Results Passed
+    #   run: |
+    #     echo "fail on purpose"
+    #     exit 1
+    - name: Check If Passed
+      id: check_result
+      if: always()
+      uses: andstor/file-existence-action@v1
+      with:
+        files: "app-debug.apk"
+    - name: ${{matrix.os}} Unit Tests
+      if: steps.check_result.outputs.files_exists == 'false' && always()
       run: |
-        echo "fail on purpose"
+        echo "${{matrix.os}} Unit Tests Failed"
         exit 1
