Testing continue on error and exit strategies

diff --git a/.github/workflows/dotnet_provisioner_unit_tests.yml b/.github/workflows/dotnet_provisioner_unit_tests.yml
--- a/.github/workflows/dotnet_provisioner_unit_tests.yml
+++ b/.github/workflows/dotnet_provisioner_unit_tests.yml
@@ -4,7 +4,6 @@ env:
   DOTNET_VERSION: '3.1'
 jobs:
   dotnet_provisioner_unit_tests:
-    name: Restore and run unit tests
     # continue-on-error: true
     runs-on: ${{ matrix.os }}
     strategy:
@@ -92,20 +91,22 @@ jobs:
 
     - name: Results Passed
       if: (steps.window_result.outputs.result == 'True' || steps.ubuntu_result.outputs.result == 'True') && always()
-      # run: |
-      #   echo "All Tests Passed"
-      #   exit 0
-      uses: dflydev/check-runs-action@v1
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        conclusion: success  
+      run: |
+        echo "All Tests Passed"
+        exit 0
+
 
     - name: Results Failed
       if: (steps.window_result.outputs.result == 'False' || steps.ubuntu_result.outputs.result == 'False') && always()
-      # run: |
-      #   echo "Unit Tests Failed"
-      #   exit 1
-      uses: dflydev/check-runs-action@v1
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        conclusion: failure
+      run: |
+        echo "Unit Tests Failed"
+        exit 1
+
+
+  evaluator:
+    runs-on: windows-latest
+    needs: [(windows-2022), (ubuntu-20.04), (windows-2019), (ubuntu-18.04)]
+    steps:
+    - name: Set git to use LF
+      run: |
+        echo "Finished"
