removed tests

diff --git a/.github/workflows/hirs_unit_tests.yml b/.github/workflows/hirs_unit_tests.yml
--- a/.github/workflows/hirs_unit_tests.yml
+++ b/.github/workflows/hirs_unit_tests.yml
@@ -54,43 +54,43 @@ jobs:
           # log into and run docker (note: must set up secrets in github for ghcr username and access_token)
           echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin
           
-          # docker run options:
-          #   create a mount between curr directory on the runner and the HIRS folder created by the cloning of HIRS repo
-          #     -v $(pwd):/HIRS
-          #   image used for the container, given by <repository>:<tag_name>
-          #     rocky9: ghcr.io/nsacyber/hirs/hirs-rocky9-ci:latest [repo: https://github.com/orgs/nsacyber/packages]
-          #   bash commands to clean/build/test each subproject
-          #     /bin/bash -c '<commands>'
-          docker run --rm \
-          -v $(pwd):/HIRS \
-          ghcr.io/nsacyber/hirs/hirs-rocky9-ci:latest /bin/bash -c \
-            'pushd /HIRS
-            gradle_status=0
-          
-            # git added a feature that gives error if user is not owner of the top-level directory; need to override this
-            git config --global --add safe.directory /HIRS
-          
-            # clean, build and run unit tests on all sub-projects; copy build reports to an artifacts directory
-          
-            ./gradlew :HIRS_AttestationCA:clean :HIRS_AttestationCA:build :HIRS_AttestationCA:test
-            if (( $? != "0" )) ; then gradle_status=1; fi
-            cp -r /HIRS/HIRS_AttestationCA/build/reports/ /HIRS/artifacts/upload_reports/HIRS_AttestationCA/.
-          
-            ./gradlew :HIRS_AttestationCAPortal:clean :HIRS_AttestationCAPortal:build :HIRS_AttestationCAPortal:test
-            if (( $? != "0" )) ; then gradle_status=1; fi
-            cp -r /HIRS/HIRS_AttestationCAPortal/build/reports/ /HIRS/artifacts/upload_reports/HIRS_AttestationCAPortal/.
-          
-            ./gradlew :HIRS_Utils:clean :HIRS_Utils:build :HIRS_Utils:test
-            if (( $? != "0" )) ; then gradle_status=1; fi
-            cp -r /HIRS/HIRS_Utils/build/reports/ /HIRS/artifacts/upload_reports/HIRS_Utils/.
-          
-            # Create "fail file" to fail the Build ACA tests if gradle exited with anything other than 0      
-            if (( $gradle_status == "0" )) ; then
-              echo "In docker: Build Passed"
-            else
-              echo "In docker: Build Failed"
-              touch /HIRS/artifacts/githubActionsResults/buildFailed.txt
-            fi; popd;'
+#          # docker run options:
+#          #   create a mount between curr directory on the runner and the HIRS folder created by the cloning of HIRS repo
+#          #     -v $(pwd):/HIRS
+#          #   image used for the container, given by <repository>:<tag_name>
+#          #     rocky9: ghcr.io/nsacyber/hirs/hirs-rocky9-ci:latest [repo: https://github.com/orgs/nsacyber/packages]
+#          #   bash commands to clean/build/test each subproject
+#          #     /bin/bash -c '<commands>'
+#          docker run --rm \
+#          -v $(pwd):/HIRS \
+#          ghcr.io/nsacyber/hirs/hirs-rocky9-ci:latest /bin/bash -c \
+#            'pushd /HIRS
+#            gradle_status=0
+#
+#            # git added a feature that gives error if user is not owner of the top-level directory; need to override this
+#            git config --global --add safe.directory /HIRS
+#
+#            # clean, build and run unit tests on all sub-projects; copy build reports to an artifacts directory
+#
+#            ./gradlew :HIRS_AttestationCA:clean :HIRS_AttestationCA:build :HIRS_AttestationCA:test
+#            if (( $? != "0" )) ; then gradle_status=1; fi
+#            cp -r /HIRS/HIRS_AttestationCA/build/reports/ /HIRS/artifacts/upload_reports/HIRS_AttestationCA/.
+#
+#            ./gradlew :HIRS_AttestationCAPortal:clean :HIRS_AttestationCAPortal:build :HIRS_AttestationCAPortal:test
+#            if (( $? != "0" )) ; then gradle_status=1; fi
+#            cp -r /HIRS/HIRS_AttestationCAPortal/build/reports/ /HIRS/artifacts/upload_reports/HIRS_AttestationCAPortal/.
+#
+#            ./gradlew :HIRS_Utils:clean :HIRS_Utils:build :HIRS_Utils:test
+#            if (( $? != "0" )) ; then gradle_status=1; fi
+#            cp -r /HIRS/HIRS_Utils/build/reports/ /HIRS/artifacts/upload_reports/HIRS_Utils/.
+#
+#            # Create "fail file" to fail the Build ACA tests if gradle exited with anything other than 0
+#            if (( $gradle_status == "0" )) ; then
+#              echo "In docker: Build Passed"
+#            else
+#              echo "In docker: Build Failed"
+#              touch /HIRS/artifacts/githubActionsResults/buildFailed.txt
+#            fi; popd;'
       # Upload build report files
       - name: Archive report files
         uses: actions/upload-artifact@v5
