Added new env variables to track failures

diff --git a/.github/workflows/system_test.yml b/.github/workflows/system_test.yml
--- a/.github/workflows/system_test.yml
+++ b/.github/workflows/system_test.yml
@@ -10,6 +10,9 @@ on:
   workflow_dispatch:
 env:
   TEST_STATUS: 0
+  FAILED_TEST_COUNT: 0
+  TEST_COUNT: 14
+  FAILED_TEST_LIST: ""
 jobs:
   DockerTests:
     runs-on: ubuntu-latest
@@ -100,6 +103,11 @@ jobs:
         shell: bash
         run: |
           .ci/system-tests/tests/rim_system_tests.sh 1
+          if [ ${TEST_STATUS} == "1" ]; then
+                ${FAILED_TEST_COUNT}++
+                ${FAILED_TEST_LIST} += "ACA RIM TEST 1 "
+          fi
+          
       - name: ACA RIM TEST 2 - Test a RIM from an OEM with a bad reference measurement and a Supplemental RIM from a VAR
         continue-on-error: true
         shell: bash
@@ -146,8 +154,11 @@ jobs:
       - name: Check System Test results
         if: success() || failure()
         run: |
-          if [ ${TEST_STATUS} == "0" ]; then
-            exit 0;
-          else
-            exit 1;
-          fi
+         if [ ${TEST_STATUS} == "0" ]; then
+            echo "All ${TEST_COUNT} test(s) passed!"
+            exit 0
+         else
+             echo "${FAILED_TEST_COUNT} out of ${TEST_COUNT} failed."
+             echo "Faled tests include: ${FAILED_TEST_LIST}"
+             exit 1
+         fi
